# -*- coding: utf-8 -*-
"""Punto_1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RyLPKr76XsXXICfinr2kBoVhA43Up0iB

##**Punto 1**
"""

def Promedio(*args) -> float:
  suma=0
  promedio=0
  for i in lista:
    suma += i
  promedio = suma/len(lista)
  return promedio

if __name__ == "__main__":
  elemento=0
  lista=[]
  j = int(input("Ingrese la cantidad de elementos que desea que tenga la lista:"))
  for elemento in range (j):
    elemento = float(input("Ingrese un valor real:"))
    lista.append(elemento)
  rta = Promedio(elemento)
  print("----------------------------------------------------------------")
  print(lista)
  print("El promedio de los valores es " + str(rta))